In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

dataset= pd.read_csv("C:\\Users\\dilee\\OneDrive\\Desktop\\study\\pantech\\Machine learning\project\\XGBOOST\\BrestcancerTumerdetection_XGBOOST-27\\dataset.csv")

dataset.shape

dataset.head(5)

x= dataset.iloc[:,:-1].values
x

y = dataset.iloc[:,-1].values
y

x_train, x_test, y_train, y_test= train_test_split(x, y, test_size=0.25, random_state=0)

In [2]:
!pip install xgboost

Defaulting to user installation because normal site-packages is not writeable


from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = le.fit_transform(y_train)

In [3]:
from xgboost import XGBClassifier
model = XGBClassifier()

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = le.fit_transform(y_train)

In [6]:
model.fit(x_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_bin=256, max_cat_threshold=64, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=0, ...)

In [14]:

from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = model.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred)*100)

[[  0   0   0   0]
 [  0   0   0   0]
 [103   4   0   0]
 [  5  59   0   0]]
0.0


In [15]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = model, X = x_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))

Accuracy: 96.29 %
